// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntdUTLqAlK1yasBk62zANwPAVHmkxiBM',
    appId: '1:883969047150:web:b9cfd7699a176390a2447f',
    messagingSenderId: '883969047150',
    projectId: 'glowup-2ae49',
    authDomain: 'glowup-2ae49.firebaseapp.com',
    storageBucket: 'glowup-2ae49.firebasestorage.app',
    measurementId: 'G-7F8X2JRZ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPSpEXQ1YjvtaCAiSW0J_QDJl2bC7X2E',
    appId: '1:883969047150:android:40f9bde9289bd196a2447f',
    messagingSenderId: '883969047150',
    projectId: 'glowup-2ae49',
    storageBucket: 'glowup-2ae49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATs7K6ckQ6YUShRleEq9XERllBawIBZHI',
    appId: '1:883969047150:ios:10956de578b98507a2447f',
    messagingSenderId: '883969047150',
    projectId: 'glowup-2ae49',
    storageBucket: 'glowup-2ae49.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATs7K6ckQ6YUShRleEq9XERllBawIBZHI',
    appId: '1:883969047150:ios:10956de578b98507a2447f',
    messagingSenderId: '883969047150',
    projectId: 'glowup-2ae49',
    storageBucket: 'glowup-2ae49.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCntdUTLqAlK1yasBk62zANwPAVHmkxiBM',
    appId: '1:883969047150:web:8c0c9c632e0d2401a2447f',
    messagingSenderId: '883969047150',
    projectId: 'glowup-2ae49',
    authDomain: 'glowup-2ae49.firebaseapp.com',
    storageBucket: 'glowup-2ae49.firebasestorage.app',
    measurementId: 'G-GG3H603VRH',
  );
}
